### ISSUE TITLE
Result of Table 3,4,5

### ISSUE THREAD

**Issue by YapheeetS** [Yueming-Yin/UMAN#1]
I try to reproduce the result of Table 3,4,5. When I add my code of loading data on UMAN, the result is quite different from that shown in the Tables. Is there any setting need to be changed from the code on Github?

Thank you.

**Comment by Yueming-Yin** [comment]
Have you added a new data reading code? Are the IDs of the source and target domains in the configuration file correct?

**Comment by Yueming-Yin** [comment]
By the way, different datasets need to use different configuration files, making sure that the label set size setting is consistent with the paper.

**Comment by YapheeetS** [comment]
Yes, I checked the code. The problem might be that I am using different files like "amazon_reorgnized.txt, dslr_reorgnized.txt, webcam_reorgnized.txt" in Office31 (It is produced by myself). So the common label sets and private label sets may different with your experiment. Can you provide the files for these datasets?

**Comment by Yueming-Yin** [comment]
I have uploaded the code ‘turn_to_list.py’ to generate the list of datasets. You can generate yours based on your path.

**Comment by YapheeetS** [comment]
Thank you. I'll try it

**Comment by YapheeetS** [comment]
Hi Yueming,

After using turn_to_list.py to generate the list of datasets, I can get relatively close result for AD-W and AW-D, but still fail DW-A on Office31 datasets.

I also tried the checkpoints provided by you (https://drive.google.com/drive/folders/15X3VY6pYZ61ZTifkshSI4QSxVZyTKgSg) and it fails on all settings(AD-W, AW-D, DW-A). I found it is still the problem with label ID definition, ex. the model always predict bike_helmet(no.2 id on my list) to the no.10 id and bookcase(no.3 id on my list) to the no.11 id. This shows list of datasets is different with my using.

**Comment by Yueming-Yin** [comment]
These are the generated lists that I used before. 
[amazon_reorgnized.txt](https://github.com/Yueming-Yin/UMAN/files/8204267/amazon_reorgnized.txt)
[dslr_reorgnized.txt](https://github.com/Yueming-Yin/UMAN/files/8204269/dslr_reorgnized.txt)
[webcam_reorgnized.txt](https://github.com/Yueming-Yin/UMAN/files/8204270/webcam_reorgnized.txt)

**Comment by YapheeetS** [comment]
Get it! Can you provide the lists for OfficeHome and VisDA2017+ImageCLEF-DA. Thanks so much!

**Comment by Yueming-Yin** [comment]
Done. See https://github.com/Yueming-Yin/UMAN/tree/main/Dataset_lists

**Comment by YapheeetS** [comment]
Thanks for your help!
